manrajgrover/halo

README.md
examples/custom_spins.py
examples/doge_spin.py
examples/persist_spin.py
halo/halo.py
tests/test_halo.py

Replaced the dict initialization of `Halo` objects with a keyword initialization.
``` python 
Halo({'text': 'Loading', 'spinner': 'dots'})
```
to
``` python 
Halo(text='Loading', spinner='dots')
```
I also made the necessary modifications on the tests, readme and examples.
(My text editor removed a lot of whitespaces, sorry about that.)

Keyword arguments to initialize Halo instances

---

requirements.txt

Following dependencies have been bumped:
1. `log_symbols`: `0.0.9` to `0.0.11`
2. `spinners `: `0.0.17` to `0.0.19`

Requirements: Dependencies updated

---

README.md
halo/__init__.py
halo/halo.py
requirements.txt
tests/test_halo.py

I added two methods to the `Halo` class: `__enter__()` and `__exit__()`. These allows spinners to be used through Python's `with` statement like so:
```python
from halo import Halo
with Halo({'text': 'Loading', 'spinner': 'dots'}):
```
---
As an aside, the way that keyword parameters are passed to the Halo class is non-Pythonic. You should just use normal kwargs with default values.

Add support for Python context managers.

---

halo/halo.py
tests/test_halo.py

Strip the text in the constructor so that if there is a newline in the text, then it won't display each step of the progress bar on a new line.

Fixes #8: Strips text before rendering

---

examples/loader_spin.py

Fix [`loader_spin.py` in examples](https://github.com/ManrajGrover/halo/blob/master/examples/loader_spin.py). In the code, `xrange` is used, but it's not compatible with python3. Although `range` method copies memory on python2, it is not a big deal.
I skipped because it was too small to open issue.

BUG FIX: Fix xrange to range in example for supporting python3

---

halo/halo.py
tests/test_halo.py

This PR resolve the issue #35. In an iPython, if a user rises `KeyboardInterrupt` without handling error statement, the cell is broken and spinner remains.
Fixed #35 refer #32
@ManrajGrover

#35: Improve keyboard interrupt handling in iPython

---

halo/halo.py

Currently, when KeyboardInterrupt is raised, handler persists current text and shows failed. We should allow user to choose the preferable output and not handle it ourselves.
Fixes #42
@JungWinter

Fixes #42: No text should be shown on KeyboardInterrupt

---

.coveragerc
examples/notebook.ipynb
halo/__init__.py
halo/halo_notebook.py
requirements.txt
tests/test_halo_notebook.py

Now, Halo in `jupyter notebook` is available by implementing `IPython widget`. If you want, test manually [on `.ipynb`](https://github.com/JungWinter/halo/blob/feature-notebook/examples/notebook.ipynb)(require download).
I tried to find the way that can test `IPython widget` in unittest. I searched the `tqdm`, but they skip tests related with `tqdm_notebook`. So in this PR, I exclude `halo_notebook.py` from coverage by modifying `.coveragerc` file. And linting test isn't still working on my machine. :( 
I have no experience with Python packaging, so I'm not sure it's ok to add dependency about `ipywidgets`. Please tell me what to do.
Discuss on #32 
@ManrajGrover

Feature #32: Available Halo in jupyter notebook

---

README.md
halo/halo.py
halo/halo_notebook.py
tests/test_halo.py
tests/test_halo_notebook.py

Adds the `placement` parameter which allows placement of the spinner on either the right or left side of the text using the values `right` and `left`.
Defaults to `left`
The only real logic changes are checking if the placement value is set to `right` and then switching the text and spinner frames in a `str.fomat` call.
```python
with Halo(text='Spinning...', placement='right') as spinner:
time.sleep(1)
Spinning... ⠧
with Halo(text='Spinning...', placement='invalid') as spinner:
time.sleep(1)
Traceback (most recent call last):
File "main.py", line 4, in <module>
with Halo('foobar', placement='invalid') as sp:
File "C:\Users\r\Documents\GitHub\halo\halo\halo.py", line 70, in __init__
self.placement = placement
File "C:\Users\r\Documents\GitHub\halo\halo\halo.py", line 193, in placement …
```

Fixes #56: Add placement parameter that allows spinner on right side of text

---

halo/_utils.py

Former fix was incomplete, so in environments without IPython at all, the `ImportError` being raised wasn't caught properly.
This PR is supposed to fix it.

Fix IPython-less mode of get_environment

---

halo/_utils.py
requirements.txt

I'm currently creating a Arch Linux AUR package for halo. Arch Linux ships with Python 3.7. Since Python 3.3 it is possible to use `get_terminal_size` directly from the `shutils` module. So it is not necessary to use the back-ported version of `get_terminal_size` for newer versions of Python. This PR will remove the dependency of `backports.shutil_get_terminal_size` for systems with Python >= 3.3 and keep the dependency for older Python versions.
I did not figure out how to run the test suite. A short developer guide might be useful.

Use get_terminal_size directly from shutil on newer Python version.

---

tests/test_halo.py

When I ran my initial tox the `test_bounce_animation` test was
failing for me because it seemed to assume that my console would
be 80 characters wide, which it was not. I used your existing
`get_terminal_columns` function to remove the assumption, and now
the test should pass regardless of the width of the tester's
console.
I also fixed a typo.
This fixes an issue [raised](https://github.com/manrajgrover/halo/pull/78#issuecomment-428096150) in [#78](https://github.com/manrajgrover/halo/pull/78).
@manrajgrover @otivvormes

BUG FIX: Fix test_bounce_animation

---

.pylintrc

This PR expands the base64-encoded pylint init hook into its full script (because INI files can do that; idk what [this guy](http://blog.algarvio.me/2012/12/27/pylint-+-virtualenv/) was smoking), and converts its usage of `execfile(path)` to `exec(open(path).read())` to support execution under Python 3.
NOTE: backslashes / continuation operators were used for indented blocks, 'cause though INI files can support multiple lines (though blank lines are removed by default), I had no idea how to also have it respect leading whitespace.
Mentioned here: https://github.com/manrajgrover/halo/issues/102#issuecomment-431643972

BUG FIX: Support pylint on Python 3

---

halo/halo.py
tests/test_halo.py

This PR foregoes returning a value from `__exit__`, thereby allowing exceptions raised inside the context manager to bubble up. Since the decorator also utilizes the context manager, exceptions will bubble up from decorated methods as well.
Resolves #102
@manrajgrover

Fixes #102: allow exceptions to bubble up w/ ctxmgr & decorator

---

requirements-dev.txt
setup.py

Fixes #31: uses latest `wheel`, `setuptools`, and `twine` to use markdown README for long_description as described [here](https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi) 
@manrajgrover @PritishSehzpaul

Fixes #31: migrate setup.py long_description to markdown README for Pypi

---

requirements.txt
setup.py

Python 3.6 introduced new package "enum".
Due to an old version of subpackage (https://github.com/manrajgrover/py-log-symbols), old "enum34" is used which is in conflict with python 3.6 ad higher.
Pull request updates the library to the newest version, which fixes the problem
See also: 
https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag
and first answer
Lint test is failing, but it is not relevant with the change
https://github.com/manrajgrover/py-log-symbols/issues/14
@manrajgrover

BUG FIX: fix python 3.6+ compatibility

---

setup.py

See #124 for the issue that this fixes.
This change has been tested with the test set out in that issue.
Fixes #124 .
@manrajgrover

BUG: Halo install requires UTF-8 locale to be set

---

README.md
examples/loader_spin.py
examples/notebook.ipynb
halo/halo.py
halo/halo_notebook.py
tests/test_halo.py
tests/test_halo_notebook.py

This PR introduces a new settable property, `Halo.enabled`, and extends the definition of "enabled" to also include whether or not the stream is closed — i.e. even if  `Halo(stream=ganges_file, enabled=True)` is passed, `Halo.enabled` will be `False` if `ganges_file.closed`. All places referencing the old `Halo._enabled` attr have been updated to use the property (like `stop` and `clear`).
Additionally, `_render_frame` in the spinner thread has been augmented to skip writing the frame text if `not Halo.enabled`.
The upshot of these changes is: running Halo under pytest is all kosher.
1. Even when `Halo.enabled is False`, I kept `_render_frame` calling `Halo.frame()` to generate the frame text and, more importantly, incrementing the frame counter, so the proper frame _in time_ would …

Fixes #97: prevent writes to closed streams

---

tests/test_halo.py
tests/test_halo_notebook.py

As in [my other PR](https://github.com/manrajgrover/halo/pull/101) for halo I've added pretty much the same test for halo notebook. `_get_test_output` has been refactored to take a `no_ansi` arg, which defaults to `True`. We then use this in the new test to keep the ANSI escape characters and compare them to those supplied by colorama.
I also cleared up an un-needed import in the other test file.
Sorry it took me a while to get to!
#81 
@manrajgrover

FIXES #81: Add tests to verify ANSI codes are in the spinner output

---

.travis.yml
appveyor.yml
requirements-dev.txt
requirements.txt
setup.py

This PR changes the versions of all requirements to greater or equal the existing version number. It currently is very easy to break halo just by installing a newer package version and pkg_config will complain. This unnecessarily restricts the number of environments in which halo can be used.
I don't think there is any reason not to do this and one can probably assume that most packages will be backwards compatible.
If you'd be okay with it I'd propose to get rid of the `requirements.txt` (and its dev version) and instead just put them in `setup.py` directly. I can offer to implement this. There is a short discussion about the merits of each approach here:
https://pip.readthedocs.io/en/1.1/requirements.html

Improvement: Don't fix the dependency versions

---

halo/halo.py
setup.py
tests/test_halo.py

I noticed that the method `Halo._write` is used everywhere, except in `Halo._stop_and_persist`, where the string is written directly to the _stream.
In pytest the output is captured and the stream gets closed after the test, so this fix was critical for me.

Use _write in stop_and_persist
