appveyor.yml, requirements.txt
This pull request fixes Windows builds on Appveyor.
=> Fixes builds and thus unicode issues on Windows

halo/__init__.py, halo/halo.py
Changed logging to recommended method in the logging howto, PEP8 fixes for import statements
=> Fixes #14: Changes logging level and reorders imports

setup.py
=> Version: Bumped to 0.0.6

setup.py
=> Version: Bumped to 0.0.7

README.md, halo/_utils.py, halo/halo.py, requirements.txt, tests/test_halo.py
Hi,
This kinda fixes #1 (text gets repeated when the text is too long for the terminal) and adds a new functionality: text animations. Like when you wget a large file and the filename scrolls around the terminal.
This new functionality is controlled with the `animations` param. For example:
```
spinner = Halo(text='This is a really large text, testing testing, this is a really large text, testing, testing.', spinner='dots', animation='marquee')
```
I added two animations, which you can see them in action here: https://asciinema.org/a/Z3Q1kMm0iQCQySVD2nuApdMKD
* `marquee` makes the text scroll, just like wget does.
* `bounce` makes it bounce back and forth.
There's a third option, which the code will always default when the text is too large for the terminal: ellipsis. This will truncate …
=> Text wrapping and animations

examples/stream_change.py, halo/halo.py, requirements.txt
This PR updates cursor library to `1.2.0` which now allows the passing stream to the library and thus does not leak escape sequences to stdout.
#36 
https://github.com/GijsTimmers/cursor/issues/2
https://github.com/GijsTimmers/cursor/pull/3
@ManrajGrover
=> Fixes #36: Escape sequences leaking on stdout

setup.py
Bumps version to `0.0.10`
NA
@ccc032
=> Version: Bumped to 0.0.10

halo/halo.py, tests/test_halo.py
Calling `Halo(interval=1000)` hasn't actually assigned the value to `self._interval`.
=> Set the spinner update interval according to the constructor parameter

halo/halo.py, tests/test_halo.py
This PR fixes #46 and does not output anything when enabled flag is set.
#46 
@vidyarani-dg
=> Fixes 46: Disable spinners when not outputting to a TTY

setup.py
This PR bumps version to v0.0.11.
None
None
=> Bumps version to v0.0.11

halo/halo.py, tests/test_halo.py
This PR adds support for custom spinners on Windows.
Fixes #49
None
=> Fixes #49: Support custom spinners on windows

setup.py
Bumps version to 0.0.12 and allows user to use custom spinner on Windows.
None
None
=> Version: Bumped to v0.0.12

examples/context_manager.py, examples/custom_spins.py, examples/doge_spin.py, examples/loader_spin.py, examples/long_text.py, examples/persist_spin.py, examples/stream_change.py
This PR fixes imports, removes unwanted imports and also cleans up code
None
None
=> Examples: Fixes imports and cleans up code

requirements.txt
This PR upgrades spinners dependency to 0.0.22.
None
None
=> Requirements: Upgrade spinners to 0.0.22

tests/_utils.py, tests/test_halo.py
This PR fixes teardown errors.
Fixes #63
None
=> Tests: Fix test teardown errors

requirements.txt, setup.py
Bumps version to 0.0.14 with spinners version upgraded to 0.0.23
NA
NA
=> Bumps version to 0.0.14 with spinners version upgraded to 0.0.23

setup.py
This PR bumps version to 0.0.15
NA
NA
=> Version: Bumped to 0.0.15

setup.py
This PR bumps version to 0.0.16
NA
NA
=> Version: Bumped to 0.0.16

.github/CONTRIBUTING.md, README.md, setup.py
This PR changes username from `ManrajGrover` to `manrajgrover`. Fixes travis badge.
NA
NA
=> Change username from ManrajGrover to manrajgrover

setup.py
This PR bumps version to `0.0.17`
NA
NA
=> Version: Bumped to 0.0.17

DEVELOPMENT.md
This PR adds initial development guidelines and fixes #74.
#74 
NA
=> Fixes #74: Adds initial Development Guidelines

.travis.yml
This PR changes travis git clone depth to 5 improving build time a little bit.
NA
@manrajgrover
=> Travis: Clone git depth of 5

appveyor.yml
This PR changes appveyor git clone depth to 5 improving build time a little bit.
NA
NA
=> Appveyor: Clone git depth of 5

appveyor.yml
This PR removes redundant command executions in Appveyor settings.
NA
NA
=> Appveyor: Remove redundant command executions

tox.ini
This PR removes duplication of commands and unnecessary `cover-html` flag.
NA
NA
=> Tox: Remove duplication of commands and unnecessary cover-html

.travis.yml, appveyor.yml, tox.ini
This PR adds various python test environments.
Fixes #80
NA
=> Tox: Adds various python test environments

.travis.yml
This PR enables Travis to cache pip dependencies.
NA
NA
=> Travis: Cache pip dependencies

halo/halo.py, tests/test_halo.py
=> Fixes 91: Show last character for bounce animation

setup.py
This PR bumps version to `0.0.18`
NA
NA
=> Version: Bumped to 0.0.18

halo/halo.py, tests/test_halo.py, tox.ini
Adds more tests and coverage
Fixes #88 
@manrajgrover
=> Tests: Add tests that will generate more coverage

.gitignore, halo/_utils.py, halo/halo.py, halo/halo_notebook.py, tests/_utils.py, tests/test_halo.py, tests/test_halo_notebook.py
Mainly removing whitespace and reordering imports, but also trying
to get rid of bare `except` occurrences. I also added `.DS_Store`
to the `.gitignore` for Mac users.
You don't appear to use flake8 in your linting process but some of
these issues seemed to violate PEP8 so I wanted to fix them, even
if only so that the warnings disappear in my own environment!
I am only able to run the py36 tests at present, and **they do not
currently pass for me** (see [my other PR](https://github.com/manrajgrover/halo/pull/99) for a fix for that test). To
keep this PR clean I have left them like that.
@manrajgrover
=> OTHERS: Fix linting issues

README.md, setup.py
This PR fixes image links for pypi documentation
NA
=> README: Fixes image links in pypi

halo/_utils.py, halo/halo.py, tests/test_halo.py
Fix #110 
Resolves #110
@manrajgrover
=> Fixes #110: Prevent UnicodeEncodeError

setup.py
This PR bumps version to `0.0.22`
NA
NA
=> Version: Bumped to 0.0.22

requirements.txt
Update `six` dependency from 1.11.0 to 1.12.0 (newest version) to reduce conflicts with popular packages like `tensorflow`.
Fixes #120 
@manrajgrover
=> Update six dependency from 1.11.0 to 1.12.0

setup.py, tox.ini
This PR bumps version to 0.0.24.
NA
NA
=> [Version] Bumped to 0.0.24

requirements.txt, setup.py
This PR upgrades log symbol dependency and also halo version to 0.0.25.
NA
NA
=> [Dependency] Upgrades log symbol dependency to 0.0.13

setup.py
This PR bumps version to 0.0.26.
Releases #107 
NA
NA
=> [Version] Bumped to v0.0.26

requirements.txt, setup.py
This PR bumps version of dependencies.
NA
NA
=> [Version] Bumped versions of dependencies

halo/cursor.py, halo/halo.py, halo/halo_notebook.py, requirements.txt
This PR removes cursor dependency. It replaces it with the code available in stackoverflow answer:
https://stackoverflow.com/a/10455937/2692667
Fixes #118
None
=> [#118] Removes cursor dependency 

setup.py
This PR makes a release `v0.0.30` removing cursor dependency.
NA
NA
=> [Release] Make a release v0.0.30

.travis.yml, DEVELOPMENT.md, appveyor.yml, setup.py, tox.ini
This PR removes support for Python 2.7 and enables testing for Python 3.8
NA
NA
=> [Issue] Removes support for Python 2.7; Enables testing for Python 3.8
